# ============================================================================
# FILE: central_dashboard.dashboard.lookml
# Section B - National Implementation Dashboard (CBC, unrestricted)
# Karmayogi Kartavya Karyakram
#
# Requires Looker 26.4+ (dashboard tabs; Looker allows at most 5). Tabs:
#   1 National Overview      - Box 1 + every panel of the HTML Implementation tab
#   2 SMT · One-Day · SLT    - one band per programme (SMT, then One-Day, then SLT)
#   3 State Drill-down       - Boxes 3, 4, 5 (+ record, districts, assessment)
#   4 SMT Targets & Roadmap  - CBC Monthly SMT Targets + HTML Target Tracker, then Roadmap 2027
#   5 Assessments & Export   - Box 9 and Box 10 (kept separate), then Box 11 full export
#
# Maps use Static Map (Regions): only the official TopoJSON is drawn, with no
# third-party basemap, so no disputed-border lines appear.
# GENERATED by gen_dashboard.py - edit the generator, not this file.
# ============================================================================

- dashboard: central_dashboard
  title: National Implementation Dashboard
  description: Capacity Building Commission - Karmayogi Kartavya Karyakram. Every State and UT, no access limits.
  layout: newspaper
  refresh: 1 hour
  crossfilter_enabled: true
  embed_style:
    background_color: '#FAF8F3'
    tile_background_color: '#FFFFFF'
    tile_text_color: '#1C2430'
    title_color: '#12233B'
    show_title: true
    text_tile_text_color: '#707A88'
  tabs:
  - name: overview
    label: National Overview
  - name: programmes
    label: SMT · One-Day · SLT
  - name: state_drill
    label: State Drill-down
  - name: targets_roadmap
    label: SMT Targets & Roadmap
  - name: assessment_export
    label: Assessments & Export
  filters:
  - name: zone
    title: Zone
    type: field_filter
    default_value: ''
    allow_multiple_values: true
    required: false
    ui_config:
      type: checkboxes
      display: popover
    model: central_dashboard
    explore: state_snapshot
    field: dim_state.zone
  - name: state
    title: State / UT
    type: field_filter
    default_value: ''
    allow_multiple_values: true
    required: false
    ui_config:
      type: tag_list
      display: popover
    model: central_dashboard
    explore: state_snapshot
    listens_to_filters: [zone]
    field: dim_state.state_name
  - name: drill_state
    title: Drill-down State
    type: field_filter
    default_value: Odisha
    allow_multiple_values: false
    required: false
    ui_config:
      type: dropdown_menu
      display: inline
    model: central_dashboard
    explore: state_snapshot
    field: dim_state.state_name
  - name: target_month
    title: Target Month
    type: field_filter
    default_value: Aug'26
    allow_multiple_values: false
    required: false
    ui_config:
      type: dropdown_menu
      display: inline
    model: central_dashboard
    explore: target_tracker
    field: target_tracker.month_label
  - name: batch_date
    title: Batch Date
    type: field_filter
    default_value: ''
    allow_multiple_values: true
    required: false
    ui_config:
      type: advanced
      display: popover
    model: central_dashboard
    explore: fact_batch_activity
    field: dim_date.date
  elements:

  # ======================================================================
  # TAB 1 - NATIONAL OVERVIEW (Box 1, and every panel of the HTML 'Implementation' tab)
  # ======================================================================
  - name: ov_header
    type: text
    body_text: <b>Programme Implementation Status</b> &mdash; state-wise rollout of the Karmayogi Kartavya Karyakram across every State and Union Territory. Status colour comes only from Table 1 of the programme Sheet; the counts beside it come from Table 2 and are never used to infer status. Figures match the client HTML (Sheet snapshot, 21 Aug 2026).
    tab_name: overview
    row: 0
    col: 0
    width: 24
    height: 2
  - name: ov_states_started
    title: States/UTs with implementation started
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_started, fact_state_snapshot.state_count]
    show_single_value_title: true
    single_value_title: States/UTs with implementation started
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '0'
    show_comparison: true
    comparison_type: progress
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of all States/UTs
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 2
    col: 0
    width: 6
    height: 3
  - name: ov_smt_trained
    title: State Master Trainers trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained, fact_state_snapshot.smt_batches]
    show_single_value_title: true
    single_value_title: State Master Trainers trained
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: SMT batches (2-day)
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 2
    col: 6
    width: 6
    height: 3
  - name: ov_one_day_trained
    title: One-Day participants trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained, fact_state_snapshot.one_day_batches]
    show_single_value_title: true
    single_value_title: One-Day participants trained
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: One-Day batches
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 2
    col: 12
    width: 6
    height: 3
  - name: ov_not_started
    title: States/UTs yet to start
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_not_started]
    show_single_value_title: true
    single_value_title: States/UTs yet to start
    custom_color_enabled: true
    custom_color: '#B04435'
    value_format: '0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 2
    col: 18
    width: 6
    height: 3
  - name: ov_programme_target
    title: Overall programme target
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.programme_target]
    show_single_value_title: true
    single_value_title: Overall programme target
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '#,##0'
    show_comparison: false
    note_state: expanded
    note_display: below
    note_text: 1,30,00,000 officials (1.3 crore), per the programme roadmap.
    tab_name: overview
    row: 5
    col: 0
    width: 6
    height: 5
  - name: ov_target_gauge
    title: Target Tracker - progress against 1.3 crore (%)
    model: central_dashboard
    explore: state_snapshot
    type: looker_column
    fields: [fact_state_snapshot.all_india, fact_state_snapshot.pct_of_programme_target_points]
    sorts: [fact_state_snapshot.all_india]
    limit: 1
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.pct_of_programme_target_points: '#D97B34'
    advanced_vis_config: "{\n  chart: {type: 'solidgauge'},\n  pane: {startAngle: -90, endAngle: 90, background: [{innerRadius: '60%', outerRadius: '100%', shape: 'arc', backgroundColor: '#E9E5D8', borderWidth: 0}]},\n  yAxis: [{min: 0, max: 100, tickAmount: 5, lineWidth: 0, labels: {format: '{value}%'}}],\n  plotOptions: {solidgauge: {innerRadius: '60%', dataLabels: {y: -25, borderWidth: 0, format: '{y:.3f}%'}}},\n  series: [{color: '#D97B34'}],\n  legend: {enabled: false}\n}"
    note_state: collapsed
    note_display: hover
    note_text: One-Day participants trained as a share of the 1.3 crore programme target, nationwide.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 5
    col: 6
    width: 9
    height: 5
  - name: ov_target_progress
    title: Officials reached against 1.3 crore
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained, fact_state_snapshot.programme_target]
    show_single_value_title: true
    single_value_title: Officials reached against 1.3 crore
    custom_color_enabled: true
    custom_color: '#D97B34'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of 1,30,00,000
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 5
    col: 15
    width: 9
    height: 5
  - name: ov_status_map
    title: India at a Glance - Implementation Status
    model: central_dashboard
    explore: state_snapshot
    type: looker_geo_choropleth
    fields: [dim_state.state_name, fact_state_snapshot.stage, fact_state_snapshot.smt_value, fact_state_snapshot.one_day_value, fact_state_snapshot.stage_code]
    sorts: [dim_state.state_name]
    limit: 500
    map: auto
    quantize_colors: true
    colors: ['#B04435', '#AD7C25', '#2F7D57']
    empty_color: '#F2EFE6'
    outer_border_color: '#5B6573'
    inner_border_color: '#FFFFFF'
    outer_border_width: 1.2
    inner_border_width: 0.8
    show_view_names: false
    note_state: expanded
    note_display: below
    note_text: 'Green: One-Day Completed. Amber: SMT Completed (One-Day pending). Red: Not Completed. Official boundaries, no basemap. The map always shows all 36 States/UTs so colours stay comparable. Hover for counts; click a State/UT to open it in the State Drill-down tab.'
    tab_name: overview
    row: 10
    col: 0
    width: 16
    height: 20
  - name: ov_status_legend
    title: Legend - States/UTs by status
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [fact_state_snapshot.stage, fact_state_snapshot.state_count, fact_state_snapshot.smt_trained, fact_state_snapshot.one_day_trained]
    sorts: [fact_state_snapshot.stage desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 10
    col: 16
    width: 8
    height: 6
  - name: ov_zone_strip
    title: Regional Implementation - North · South · East · West
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.zone, fact_state_snapshot.state_count, fact_state_snapshot.states_started, fact_state_snapshot.states_one_day, fact_state_snapshot.states_smt_only, fact_state_snapshot.states_not_started, fact_state_snapshot.smt_trained, fact_state_snapshot.one_day_trained]
    sorts: [dim_state.zone]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    series_labels:
      fact_state_snapshot.state_count: States/UTs
      fact_state_snapshot.states_started: Started
      fact_state_snapshot.states_one_day: Green
      fact_state_snapshot.states_smt_only: Amber
      fact_state_snapshot.states_not_started: Red
      fact_state_snapshot.smt_trained: SMT
      fact_state_snapshot.one_day_trained: 1-Day
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 16
    col: 16
    width: 8
    height: 7
  - name: ov_small_states
    title: Smaller States & Union Territories
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, fact_state_snapshot.stage, fact_state_snapshot.smt_value, fact_state_snapshot.one_day_value]
    filters:
      fact_state_snapshot.is_small_state: 'Yes'
    sorts: [dim_state.state_name]
    limit: 500
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    note_state: collapsed
    note_display: hover
    note_text: Listed separately because they are too small to click reliably on the map.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 23
    col: 16
    width: 8
    height: 7
  - name: ov_started_list
    title: Started
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, fact_state_snapshot.stage, fact_state_snapshot.smt_value, fact_state_snapshot.one_day_value]
    filters:
      fact_state_snapshot.has_started: 'Yes'
    sorts: [fact_state_snapshot.one_day_value desc, fact_state_snapshot.smt_value desc]
    limit: 500
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 30
    col: 0
    width: 12
    height: 10
  - name: ov_not_started_list
    title: Yet to Start
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, fact_state_snapshot.stage]
    filters:
      fact_state_snapshot.has_started: 'No'
    sorts: [dim_state.state_name]
    limit: 500
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 30
    col: 12
    width: 12
    height: 10
  - name: ov_data_quality
    title: Data quality notes - Table 1 / Table 2 mismatches
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, fact_state_snapshot.smt_status, fact_state_snapshot.one_day_status, fact_state_snapshot.smt_value, fact_state_snapshot.one_day_value, fact_state_snapshot.mismatch_note]
    filters:
      fact_state_snapshot.has_mismatch: 'Yes'
    sorts: [dim_state.state_name]
    limit: 500
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    note_state: collapsed
    note_display: hover
    note_text: Empty means Table 1 status and Table 2 counts agree for every State/UT. Mismatches are reported, never silently reconciled.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 40
    col: 0
    width: 24
    height: 4
  - name: ov_journey_header
    type: text
    body_text: <b>Implementation Journey</b>
    tab_name: overview
    row: 44
    col: 0
    width: 24
    height: 1
  - name: ov_journey_1
    title: States/UTs in the SMT ecosystem or beyond
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_started]
    show_single_value_title: true
    single_value_title: States/UTs in the SMT ecosystem or beyond
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 45
    col: 0
    width: 6
    height: 3
  - name: ov_journey_2
    title: State Master Trainers trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained]
    show_single_value_title: true
    single_value_title: State Master Trainers trained
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 45
    col: 6
    width: 6
    height: 3
  - name: ov_journey_3
    title: States/UTs running One-Day training
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_one_day]
    show_single_value_title: true
    single_value_title: States/UTs running One-Day training
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 45
    col: 12
    width: 6
    height: 3
  - name: ov_journey_4
    title: Frontline officials reached
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained]
    show_single_value_title: true
    single_value_title: Frontline officials reached
    custom_color_enabled: true
    custom_color: '#D97B34'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 45
    col: 18
    width: 6
    height: 3
  - name: ov_certification_trend
    title: Certification Trend - split by programme (batches by month)
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_line
    fields: [dim_date.month_name, fact_batch_activity.smt_batches, fact_batch_activity.one_day_batches]
    sorts: [dim_date.month_name]
    limit: 500
    show_value_labels: false
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.smt_batches: '#1D3557'
      fact_batch_activity.one_day_batches: '#D97B34'
    series_labels:
      fact_batch_activity.smt_batches: State Master Trainer batches (2-day)
      fact_batch_activity.one_day_batches: 1-Day Participant batches
    point_style: circle
    interpolation: linear
    note_state: collapsed
    note_display: hover
    note_text: Two lines, month-wise. Batch dates are partly demo where the Sheet had none; totals reconcile to the Sheet.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: overview
    row: 48
    col: 0
    width: 24
    height: 8
  - name: ov_top10_one_day
    title: Top 10 States - One-Day participants
    model: central_dashboard
    explore: state_snapshot
    type: looker_bar
    fields: [dim_state.state_name, fact_state_snapshot.one_day_trained]
    filters:
      fact_state_snapshot.one_day_trained: '>0'
    sorts: [fact_state_snapshot.one_day_trained desc]
    limit: 10
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.one_day_trained: '#2F7D57'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 56
    col: 0
    width: 12
    height: 9
  - name: ov_top10_smt
    title: Top 10 States - State Master Trainers
    model: central_dashboard
    explore: state_snapshot
    type: looker_bar
    fields: [dim_state.state_name, fact_state_snapshot.smt_trained]
    filters:
      fact_state_snapshot.smt_trained: '>0'
    sorts: [fact_state_snapshot.smt_trained desc]
    limit: 10
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.smt_trained: '#AD7C25'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 56
    col: 12
    width: 12
    height: 9
  - name: ov_statewise_one_day
    title: State-wise Progress - One-Day Participants (all started States/UTs)
    model: central_dashboard
    explore: state_snapshot
    type: looker_bar
    fields: [dim_state.state_name, fact_state_snapshot.one_day_trained]
    filters:
      fact_state_snapshot.has_started: 'Yes'
    sorts: [fact_state_snapshot.one_day_trained desc]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.one_day_trained: '#2F7D57'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 65
    col: 0
    width: 12
    height: 12
  - name: ov_statewise_smt
    title: State-wise Progress - SMTs Trained (all started States/UTs)
    model: central_dashboard
    explore: state_snapshot
    type: looker_bar
    fields: [dim_state.state_name, fact_state_snapshot.smt_trained]
    filters:
      fact_state_snapshot.has_started: 'Yes'
    sorts: [fact_state_snapshot.smt_trained desc]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.smt_trained: '#AD7C25'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 65
    col: 12
    width: 12
    height: 12
  - name: ov_cluster_smt
    title: Cluster Comparison - State Master Trainers
    model: central_dashboard
    explore: state_snapshot
    type: looker_column
    fields: [dim_state.zone, fact_state_snapshot.smt_trained]
    sorts: [dim_state.zone]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.smt_trained: '#AD7C25'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 77
    col: 0
    width: 12
    height: 7
  - name: ov_cluster_one_day
    title: Cluster Comparison - One-Day Participants
    model: central_dashboard
    explore: state_snapshot
    type: looker_column
    fields: [dim_state.zone, fact_state_snapshot.one_day_trained]
    sorts: [dim_state.zone]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.one_day_trained: '#2F7D57'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 77
    col: 12
    width: 12
    height: 7
  - name: ov_every_state
    title: Every State and UT - full implementation record
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, dim_state.state_type, fact_state_snapshot.stage, fact_state_snapshot.smt_status, fact_state_snapshot.one_day_status, fact_state_snapshot.smt_trained, fact_state_snapshot.smt_batches, fact_state_snapshot.one_day_trained, fact_state_snapshot.one_day_batches, fact_state_snapshot.smt_required, fact_state_snapshot.frontline_target]
    sorts: [dim_state.zone, dim_state.state_name]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 84
    col: 0
    width: 24
    height: 14

  # ======================================================================
  # TAB 2 - STATE MASTER TRAINERS (every SMT view in one place)
  # ======================================================================
  - name: smt_header
    type: text
    body_text: <b>State Master Trainers (2-day programme)</b> &mdash; SMTs trained against the requirement to March 2027. SMT assessment results are on the Assessments tab (Box 10); monthly SMT targets are on the Monthly SMT Targets tab.
    tab_name: programmes
    row: 0
    col: 0
    width: 24
    height: 2
  - name: smt_kpi_trained
    title: SMTs trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained]
    show_single_value_title: true
    single_value_title: SMTs trained
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 2
    col: 0
    width: 4
    height: 3
  - name: smt_kpi_batches
    title: SMT batches conducted
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_batches]
    show_single_value_title: true
    single_value_title: SMT batches conducted
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 2
    col: 4
    width: 4
    height: 3
  - name: smt_kpi_states
    title: States/UTs with SMT completed
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_started, fact_state_snapshot.state_count]
    show_single_value_title: true
    single_value_title: States/UTs with SMT completed
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '0'
    show_comparison: true
    comparison_type: progress
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of all States/UTs
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 2
    col: 8
    width: 4
    height: 3
  - name: smt_kpi_required
    title: Progress to SMT requirement
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained, fact_state_snapshot.smt_required]
    show_single_value_title: true
    single_value_title: Progress to SMT requirement
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of SMTs required by Mar'27
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 2
    col: 12
    width: 4
    height: 3
  - name: smt_kpi_outstanding
    title: SMTs still to train
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_still_required]
    show_single_value_title: true
    single_value_title: SMTs still to train
    custom_color_enabled: true
    custom_color: '#B04435'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 2
    col: 16
    width: 4
    height: 3
  - name: smt_kpi_batches_req
    title: SMT batches required
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_batches_required]
    show_single_value_title: true
    single_value_title: SMT batches required
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 2
    col: 20
    width: 4
    height: 3
  - name: smt_map
    title: SMTs trained by State/UT
    model: central_dashboard
    explore: state_snapshot
    type: looker_geo_choropleth
    fields: [dim_state.state_name, fact_state_snapshot.stage, fact_state_snapshot.smt_batches_value, fact_state_snapshot.smt_required_value, fact_state_snapshot.smt_trained]
    sorts: [dim_state.state_name]
    limit: 500
    map: auto
    quantize_colors: false
    colors: ['#F3EBD9', '#E3C98F', '#AD7C25', '#6E4E14']
    empty_color: '#F2EFE6'
    outer_border_color: '#5B6573'
    inner_border_color: '#FFFFFF'
    outer_border_width: 1.2
    inner_border_width: 0.8
    show_view_names: false
    note_state: expanded
    note_display: below
    note_text: Darker = more SMTs trained. Pale = none yet. Always shows all 36 States/UTs.
    tab_name: programmes
    row: 5
    col: 0
    width: 14
    height: 18
  - name: smt_top10
    title: Top 10 States - SMTs trained
    model: central_dashboard
    explore: state_snapshot
    type: looker_bar
    fields: [dim_state.state_name, fact_state_snapshot.smt_trained]
    filters:
      fact_state_snapshot.smt_trained: '>0'
    sorts: [fact_state_snapshot.smt_trained desc]
    limit: 10
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.smt_trained: '#AD7C25'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 5
    col: 14
    width: 10
    height: 9
  - name: smt_by_zone
    title: SMTs and SMT batches by zone
    model: central_dashboard
    explore: state_snapshot
    type: looker_column
    fields: [dim_state.zone, fact_state_snapshot.smt_trained, fact_state_snapshot.smt_batches]
    sorts: [dim_state.zone]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.smt_trained: '#AD7C25'
      fact_state_snapshot.smt_batches: '#1D3557'
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 14
    col: 14
    width: 10
    height: 9
  - name: smt_trend
    title: SMT training by month
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_column
    fields: [dim_date.month_name, fact_batch_activity.smt_trained, fact_batch_activity.smt_batches]
    sorts: [dim_date.month_name]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.smt_trained: '#AD7C25'
      fact_batch_activity.smt_batches: '#1D3557'
    y_axes:
    - label: SMTs trained
      orientation: left
      series:
      - id: fact_batch_activity.smt_trained
    - label: Batches
      orientation: right
      series:
      - id: fact_batch_activity.smt_batches
    note_state: collapsed
    note_display: hover
    note_text: Batch dates are partly demo where the Sheet had none.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: programmes
    row: 23
    col: 0
    width: 24
    height: 7
  - name: smt_by_group
    title: SMTs trained by service group
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_bar
    fields: [dim_group.group_name, fact_batch_activity.smt_trained]
    sorts: [dim_group.group_name]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.smt_trained: '#AD7C25'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: programmes
    row: 30
    col: 0
    width: 12
    height: 8
  - name: smt_by_designation
    title: SMTs trained by designation (top 15)
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_bar
    fields: [dim_designation.designation_name, fact_batch_activity.smt_trained]
    filters:
      fact_batch_activity.smt_trained: '>0'
    sorts: [fact_batch_activity.smt_trained desc]
    limit: 15
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.smt_trained: '#1D3557'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: programmes
    row: 30
    col: 12
    width: 12
    height: 8
  - name: smt_state_table
    title: SMT record by State/UT
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, fact_state_snapshot.smt_status, fact_state_snapshot.smt_trained, fact_state_snapshot.smt_batches, fact_state_snapshot.smt_required, fact_state_snapshot.pct_smt_requirement, fact_state_snapshot.smt_still_required, fact_state_snapshot.smt_batches_required]
    sorts: [fact_state_snapshot.smt_trained desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 38
    col: 0
    width: 24
    height: 12

  # ======================================================================
  # TAB 3 - ONE-DAY PARTICIPANT PROGRAMME (every One-Day view in one place)
  # ======================================================================
  - name: od_header
    type: text
    body_text: <b>One-Day Participant Programme</b> &mdash; frontline officials trained, against each State's frontline target and the 1.3 crore national target. One-Day assessment results are on the Assessments tab (Box 9).
    tab_name: programmes
    row: 50
    col: 0
    width: 24
    height: 2
  - name: od_kpi_trained
    title: One-Day participants trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained]
    show_single_value_title: true
    single_value_title: One-Day participants trained
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 52
    col: 0
    width: 4
    height: 3
  - name: od_kpi_batches
    title: One-Day batches conducted
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_batches]
    show_single_value_title: true
    single_value_title: One-Day batches conducted
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 52
    col: 4
    width: 4
    height: 3
  - name: od_kpi_states
    title: States/UTs running One-Day
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_one_day, fact_state_snapshot.state_count]
    show_single_value_title: true
    single_value_title: States/UTs running One-Day
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '0'
    show_comparison: true
    comparison_type: progress
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of all States/UTs
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 52
    col: 8
    width: 4
    height: 3
  - name: od_kpi_programme
    title: Progress to 1.3 crore
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.pct_of_programme_target]
    show_single_value_title: true
    single_value_title: Progress to 1.3 crore
    custom_color_enabled: true
    custom_color: '#D97B34'
    value_format: 0.000%
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 52
    col: 12
    width: 4
    height: 3
  - name: od_kpi_frontline
    title: Frontline target (State plans)
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.frontline_target]
    show_single_value_title: true
    single_value_title: Frontline target (State plans)
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 52
    col: 16
    width: 4
    height: 3
  - name: od_kpi_frontline_pct
    title: Frontline target reached
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.pct_frontline_reached]
    show_single_value_title: true
    single_value_title: Frontline target reached
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: 0.00%
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 52
    col: 20
    width: 4
    height: 3
  - name: od_map
    title: One-Day participants by State/UT
    model: central_dashboard
    explore: state_snapshot
    type: looker_geo_choropleth
    fields: [dim_state.state_name, fact_state_snapshot.stage, fact_state_snapshot.one_day_batches_value, fact_state_snapshot.frontline_value, fact_state_snapshot.one_day_trained]
    sorts: [dim_state.state_name]
    limit: 500
    map: auto
    quantize_colors: false
    colors: ['#E4F1E9', '#9FCCB2', '#2F7D57', '#17452F']
    empty_color: '#F2EFE6'
    outer_border_color: '#5B6573'
    inner_border_color: '#FFFFFF'
    outer_border_width: 1.2
    inner_border_width: 0.8
    show_view_names: false
    note_state: expanded
    note_display: below
    note_text: Darker = more One-Day participants trained. Pale = none yet. Always shows all 36 States/UTs.
    tab_name: programmes
    row: 55
    col: 0
    width: 14
    height: 18
  - name: od_top10
    title: Top 10 States - One-Day participants
    model: central_dashboard
    explore: state_snapshot
    type: looker_bar
    fields: [dim_state.state_name, fact_state_snapshot.one_day_trained]
    filters:
      fact_state_snapshot.one_day_trained: '>0'
    sorts: [fact_state_snapshot.one_day_trained desc]
    limit: 10
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.one_day_trained: '#2F7D57'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 55
    col: 14
    width: 10
    height: 9
  - name: od_by_zone
    title: One-Day participants and batches by zone
    model: central_dashboard
    explore: state_snapshot
    type: looker_column
    fields: [dim_state.zone, fact_state_snapshot.one_day_trained, fact_state_snapshot.one_day_batches]
    sorts: [dim_state.zone]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.one_day_trained: '#2F7D57'
      fact_state_snapshot.one_day_batches: '#1D3557'
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 64
    col: 14
    width: 10
    height: 9
  - name: od_trend
    title: One-Day training by month
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_column
    fields: [dim_date.month_name, fact_batch_activity.one_day_trained, fact_batch_activity.one_day_batches]
    sorts: [dim_date.month_name]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.one_day_trained: '#2F7D57'
      fact_batch_activity.one_day_batches: '#1D3557'
    y_axes:
    - label: Participants
      orientation: left
      series:
      - id: fact_batch_activity.one_day_trained
    - label: Batches
      orientation: right
      series:
      - id: fact_batch_activity.one_day_batches
    note_state: collapsed
    note_display: hover
    note_text: Batch dates are partly demo where the Sheet had none.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: programmes
    row: 73
    col: 0
    width: 24
    height: 7
  - name: od_by_group
    title: One-Day trained by service group (national)
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_bar
    fields: [dim_group.group_name, fact_batch_activity.one_day_trained]
    sorts: [dim_group.group_name]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.one_day_trained: '#2F7D57'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: programmes
    row: 80
    col: 0
    width: 12
    height: 8
  - name: od_by_designation
    title: One-Day trained by designation (top 15, national)
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_bar
    fields: [dim_designation.designation_name, fact_batch_activity.one_day_trained]
    filters:
      fact_batch_activity.one_day_trained: '>0'
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 15
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.one_day_trained: '#1D3557'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: programmes
    row: 80
    col: 12
    width: 12
    height: 8
  - name: od_state_table
    title: One-Day record by State/UT
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, fact_state_snapshot.one_day_status, fact_state_snapshot.one_day_trained, fact_state_snapshot.one_day_batches, fact_state_snapshot.frontline_target, fact_state_snapshot.pct_frontline_reached, fact_state_snapshot.frontline_still_to_reach]
    sorts: [fact_state_snapshot.one_day_trained desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 88
    col: 0
    width: 24
    height: 12

  # ======================================================================
  # TAB 4 - STATE LEAD TRAINERS (every SLT view in one place)
  # ======================================================================
  - name: slt_header
    type: text
    body_text: <b>State Lead Trainers</b> &mdash; requirement to March 2027 from the Target tab of the Sheet. The Sheet has no column for SLTs trained, so the current figure reads <i>Data not available</i> rather than a guessed number or zero.
    tab_name: programmes
    row: 100
    col: 0
    width: 24
    height: 2
  - name: slt_kpi_required
    title: SLTs required by Mar'27
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.slt_required]
    show_single_value_title: true
    single_value_title: SLTs required by Mar'27
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 102
    col: 0
    width: 8
    height: 3
  - name: slt_kpi_trained
    title: SLTs trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.slt_trained]
    show_single_value_title: true
    single_value_title: SLTs trained
    custom_color_enabled: true
    custom_color: '#707A88'
    show_comparison: false
    note_state: expanded
    note_display: below
    note_text: No SLT-trained figure exists yet in the source Sheet.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 102
    col: 8
    width: 8
    height: 3
  - name: slt_kpi_batches
    title: SLT batches required
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.slt_batches_required]
    show_single_value_title: true
    single_value_title: SLT batches required
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 102
    col: 16
    width: 8
    height: 3
  - name: slt_map
    title: SLTs required by State/UT
    model: central_dashboard
    explore: state_snapshot
    type: looker_geo_choropleth
    fields: [dim_state.state_name, fact_state_snapshot.slt_batches_required_value, fact_state_snapshot.smt_required_value, fact_state_snapshot.slt_required]
    sorts: [dim_state.state_name]
    limit: 500
    map: auto
    quantize_colors: false
    colors: ['#E8EDF4', '#9DB0CC', '#1D3557', '#12233B']
    empty_color: '#F2EFE6'
    outer_border_color: '#5B6573'
    inner_border_color: '#FFFFFF'
    outer_border_width: 1.2
    inner_border_width: 0.8
    show_view_names: false
    note_state: expanded
    note_display: below
    note_text: Darker = more State Lead Trainers required. Always shows all 36 States/UTs.
    tab_name: programmes
    row: 105
    col: 0
    width: 12
    height: 16
  - name: slt_by_zone
    title: SLT requirement by zone
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.zone, fact_state_snapshot.state_count, fact_state_snapshot.slt_required, fact_state_snapshot.slt_batches_required, fact_state_snapshot.slt_trained]
    sorts: [dim_state.zone]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 105
    col: 12
    width: 12
    height: 8
  - name: slt_top10
    title: Top 10 States - SLTs required
    model: central_dashboard
    explore: state_snapshot
    type: looker_bar
    fields: [dim_state.state_name, fact_state_snapshot.slt_required]
    sorts: [fact_state_snapshot.slt_required desc]
    limit: 10
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_state_snapshot.slt_required: '#1D3557'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 113
    col: 12
    width: 12
    height: 8
  - name: slt_state_table
    title: SLT requirement by State/UT
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, fact_state_snapshot.slt_required, fact_state_snapshot.slt_batches_required, fact_state_snapshot.slt_trained, fact_state_snapshot.smt_required, fact_state_snapshot.frontline_target]
    sorts: [fact_state_snapshot.slt_required desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 121
    col: 0
    width: 24
    height: 12

  # ======================================================================
  # TAB 5 - STATE DRILL-DOWN (Section A Boxes 1-6 for any State, no access limits)
  # ======================================================================
  - name: drill_header
    type: text
    body_text: '<b>State drill-down</b> &mdash; pick any State/UT in the <b>Drill-down State</b> filter (or click a State on any map). Everything on this tab is for that State only: its full record, Box 3 activity trend, Box 4 group-wise and Box 5 designation-wise data, districts, monthly SMT targets and its assessments.'
    tab_name: state_drill
    row: 0
    col: 0
    width: 24
    height: 2
  - name: drill_record
    title: State record
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.state_type, dim_state.zone, dim_state.programme_coordinator, fact_state_snapshot.stage, fact_state_snapshot.smt_status, fact_state_snapshot.one_day_status, fact_state_snapshot.smt_value, fact_state_snapshot.smt_batches_value, fact_state_snapshot.one_day_value, fact_state_snapshot.one_day_batches_value, fact_state_snapshot.frontline_value, fact_state_snapshot.smt_required_value, fact_state_snapshot.slt_required_value, fact_state_snapshot.smt_batches_required_value, fact_state_snapshot.smt_till_aug_value, fact_state_snapshot.slt_trained_text, fact_state_snapshot.mismatch_note]
    sorts: [dim_state.state_name]
    limit: 500
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    transpose: true
    listen:
      drill_state: dim_state.state_name
    tab_name: state_drill
    row: 2
    col: 0
    width: 8
    height: 13
  - name: drill_kpi_smt
    title: SMTs trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained, fact_state_snapshot.smt_batches]
    show_single_value_title: true
    single_value_title: SMTs trained
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: SMT batches
    listen:
      drill_state: dim_state.state_name
    tab_name: state_drill
    row: 2
    col: 8
    width: 4
    height: 3
  - name: drill_kpi_one_day
    title: One-Day trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained, fact_state_snapshot.one_day_batches]
    show_single_value_title: true
    single_value_title: One-Day trained
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: One-Day batches
    listen:
      drill_state: dim_state.state_name
    tab_name: state_drill
    row: 2
    col: 12
    width: 4
    height: 3
  - name: drill_kpi_frontline
    title: Frontline reach
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained, fact_state_snapshot.frontline_target]
    show_single_value_title: true
    single_value_title: Frontline reach
    custom_color_enabled: true
    custom_color: '#D97B34'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of State frontline target
    listen:
      drill_state: dim_state.state_name
    tab_name: state_drill
    row: 2
    col: 16
    width: 4
    height: 3
  - name: drill_kpi_smt_req
    title: SMT requirement
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained, fact_state_snapshot.smt_required]
    show_single_value_title: true
    single_value_title: SMT requirement
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of SMTs required
    listen:
      drill_state: dim_state.state_name
    tab_name: state_drill
    row: 2
    col: 20
    width: 4
    height: 3
  - name: drill_box3_activity
    title: 'Box 3 - Activity trend: batches and 1-Day trained, by date'
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_line
    fields: [fact_batch_activity.batch_date, fact_batch_activity.batch_count, fact_batch_activity.one_day_trained]
    sorts: [fact_batch_activity.batch_date]
    limit: 1000
    show_value_labels: false
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.batch_count: '#1D3557'
      fact_batch_activity.one_day_trained: '#D97B34'
    series_labels:
      fact_batch_activity.batch_count: Batches (both programmes)
      fact_batch_activity.one_day_trained: 1-Day trained
    point_style: circle
    interpolation: linear
    y_axes:
    - label: Batches
      orientation: left
      series:
      - id: fact_batch_activity.batch_count
    - label: 1-Day trained
      orientation: right
      series:
      - id: fact_batch_activity.one_day_trained
    note_state: collapsed
    note_display: hover
    note_text: Batch dates are partly demo where the Sheet had none.
    listen:
      drill_state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: state_drill
    row: 5
    col: 8
    width: 16
    height: 10
  - name: drill_box4_group
    title: 'Box 4 - Group-wise data: 1-Day trained by group'
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_bar
    fields: [dim_group.group_name, fact_batch_activity.one_day_trained]
    filters:
      fact_batch_activity.batch_type: One-Day
    sorts: [dim_group.group_name]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.one_day_trained: '#1D3557'
    hide_legend: true
    listen:
      drill_state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: state_drill
    row: 15
    col: 0
    width: 12
    height: 8
  - name: drill_box5_designation
    title: 'Box 5 - Designation-wise data: 1-Day trained by designation (top 20)'
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_bar
    fields: [dim_designation.designation_name, fact_batch_activity.one_day_trained]
    filters:
      fact_batch_activity.batch_type: One-Day
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 20
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_batch_activity.one_day_trained: '#2F7D57'
    hide_legend: true
    listen:
      drill_state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: state_drill
    row: 15
    col: 12
    width: 12
    height: 8
  - name: drill_designation_table
    title: Every designation in this State
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_designation.designation_name, dim_group.group_name, fact_batch_activity.one_day_trained, fact_batch_activity.smt_trained]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      drill_state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: state_drill
    row: 23
    col: 0
    width: 12
    height: 10
  - name: drill_district_table
    title: By district
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_district.district_name, fact_batch_activity.smt_trained, fact_batch_activity.smt_batches, fact_batch_activity.one_day_trained, fact_batch_activity.one_day_batches]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      drill_state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: state_drill
    row: 23
    col: 12
    width: 12
    height: 10
  - name: drill_monthly_targets
    title: Monthly SMT batch targets for this State
    model: central_dashboard
    explore: fact_monthly_target
    type: looker_column
    fields: [fact_monthly_target.month_label, fact_monthly_target.smt_target]
    filters:
      fact_monthly_target.month_id: 2026-08,2026-09,2026-10,2026-11,2026-12,2027-01,2027-02
    sorts: [fact_monthly_target.month_label]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_monthly_target.smt_target: '#1D3557'
    hide_legend: true
    listen:
      drill_state: dim_state.state_name
    tab_name: state_drill
    row: 33
    col: 0
    width: 12
    height: 8
  - name: drill_assessment
    title: Assessment for this State (demo scores)
    model: central_dashboard
    explore: fact_assessment
    type: looker_grid
    fields: [fact_assessment.programme_type, fact_assessment.participants_assessed, fact_assessment.weighted_baseline_score, fact_assessment.weighted_day1_score, fact_assessment.weighted_improvement, fact_assessment.certified_count, fact_assessment.not_certified_count]
    sorts: [fact_assessment.programme_type]
    limit: 500
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    note_state: collapsed
    note_display: hover
    note_text: The Sheet has no assessment feed yet; every score is DEMO.
    listen:
      drill_state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: state_drill
    row: 33
    col: 12
    width: 12
    height: 8

  # ======================================================================
  # TAB 6 - MONTHLY SMT TARGETS (CBC only) and the HTML 'Target Tracker' tab
  # ======================================================================
  - name: tg_header
    type: text
    body_text: <b>Monthly SMT targets</b> &mdash; straight from the Target tab of the Sheet. Pick a month in the <b>Target Month</b> filter. Achieved at any month counts; a concluded month that missed is red; the current month is in progress; later months are upcoming. March 2027 has no per-State column and is covered on the Roadmap 2027 tab.
    tab_name: targets_roadmap
    row: 0
    col: 0
    width: 24
    height: 2
  - name: tg_kpi_achieved
    title: Target Achieved
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_achieved]
    show_single_value_title: true
    single_value_title: Target Achieved
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '0'
    show_comparison: false
    listen:
      target_month: target_tracker.month_label
    tab_name: targets_roadmap
    row: 2
    col: 0
    width: 4
    height: 3
  - name: tg_kpi_not_achieved
    title: Target Not Achieved
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_not_achieved]
    show_single_value_title: true
    single_value_title: Target Not Achieved
    custom_color_enabled: true
    custom_color: '#B04435'
    value_format: '0'
    show_comparison: false
    listen:
      target_month: target_tracker.month_label
    tab_name: targets_roadmap
    row: 2
    col: 4
    width: 4
    height: 3
  - name: tg_kpi_in_progress
    title: In Progress
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_in_progress]
    show_single_value_title: true
    single_value_title: In Progress
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '0'
    show_comparison: false
    listen:
      target_month: target_tracker.month_label
    tab_name: targets_roadmap
    row: 2
    col: 8
    width: 4
    height: 3
  - name: tg_kpi_upcoming
    title: Upcoming
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_upcoming]
    show_single_value_title: true
    single_value_title: Upcoming
    custom_color_enabled: true
    custom_color: '#707A88'
    value_format: '0'
    show_comparison: false
    listen:
      target_month: target_tracker.month_label
    tab_name: targets_roadmap
    row: 2
    col: 12
    width: 4
    height: 3
  - name: tg_kpi_na
    title: No target set
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_not_applicable]
    show_single_value_title: true
    single_value_title: No target set
    custom_color_enabled: true
    custom_color: '#707A88'
    value_format: '0'
    show_comparison: false
    listen:
      target_month: target_tracker.month_label
    tab_name: targets_roadmap
    row: 2
    col: 16
    width: 4
    height: 3
  - name: tg_kpi_batches
    title: SMT batch target (month)
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.target_batches, target_tracker.target_smts]
    show_single_value_title: true
    single_value_title: SMT batch target (month)
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: SMTs (headcount)
    listen:
      target_month: target_tracker.month_label
    tab_name: targets_roadmap
    row: 2
    col: 20
    width: 4
    height: 3
  - name: tg_map
    title: Regional Target Performance - selected month
    model: central_dashboard
    explore: target_tracker
    type: looker_geo_choropleth
    fields: [dim_state.state_name, target_tracker.target_status, target_tracker.target_smts_value, target_tracker.smt_trained_value, target_tracker.status_code]
    sorts: [dim_state.state_name]
    limit: 500
    map: auto
    quantize_colors: true
    colors: ['#D9D5C9', '#B04435', '#AD7C25', '#2F7D57']
    empty_color: '#F2EFE6'
    outer_border_color: '#5B6573'
    inner_border_color: '#FFFFFF'
    outer_border_width: 1.2
    inner_border_width: 0.8
    show_view_names: false
    note_state: expanded
    note_display: below
    note_text: 'Green: achieved. Red: concluded and missed. Amber: current month, in progress. Grey: upcoming, or no target set. Always shows all 36 States/UTs.'
    listen:
      target_month: target_tracker.month_label
    tab_name: targets_roadmap
    row: 5
    col: 0
    width: 14
    height: 18
  - name: tg_zone_performance
    title: Target performance by zone
    model: central_dashboard
    explore: target_tracker
    type: looker_grid
    fields: [dim_state.zone, target_tracker.states_applicable, target_tracker.states_achieved, target_tracker.states_not_achieved, target_tracker.states_in_progress, target_tracker.states_upcoming, target_tracker.states_not_applicable]
    sorts: [dim_state.zone]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    series_labels:
      target_tracker.states_applicable: With target
      target_tracker.states_achieved: Achieved
      target_tracker.states_not_achieved: Missed
      target_tracker.states_in_progress: In prog.
      target_tracker.states_upcoming: Upcoming
      target_tracker.states_not_applicable: No target
    listen:
      target_month: target_tracker.month_label
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 5
    col: 14
    width: 10
    height: 8
  - name: tg_state_detail
    title: State target detail - selected month
    model: central_dashboard
    explore: target_tracker
    type: looker_grid
    fields: [dim_state.state_name, target_tracker.target_status, target_tracker.target_batches_value, target_tracker.target_smts_value, target_tracker.smt_trained_value]
    sorts: [dim_state.state_name]
    limit: 500
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    series_labels:
      target_tracker.target_batches_value: Batches
      target_tracker.target_smts_value: Target SMTs
      target_tracker.smt_trained_value: Trained
    listen:
      target_month: target_tracker.month_label
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 13
    col: 14
    width: 10
    height: 10
  - name: tg_requirement
    title: State-wise requirement (from the Sheet)
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, fact_state_snapshot.frontline_target, fact_state_snapshot.smt_required, fact_state_snapshot.slt_required, fact_state_snapshot.smt_batches_required]
    sorts: [fact_state_snapshot.frontline_target desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    series_labels:
      dim_state.state_name: State
      fact_state_snapshot.frontline_target: Minimum Target Frontline Workers
      fact_state_snapshot.smt_required: Minimum Total SMTs Reqd
      fact_state_snapshot.slt_required: Minimum Total SLTs Reqd
      fact_state_snapshot.smt_batches_required: Minimum Total SMT Batches Reqd
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 23
    col: 0
    width: 24
    height: 11
  - name: tg_month_by_month
    title: Month-by-month SMT batch targets (Aug'26 to Feb'27)
    model: central_dashboard
    explore: fact_monthly_target
    type: looker_grid
    fields: [dim_state.state_name, fact_state_snapshot.frontline_value, fact_state_snapshot.smt_till_aug_value, fact_monthly_target.month_label, fact_monthly_target.smt_target]
    pivots: [fact_monthly_target.month_label]
    filters:
      fact_monthly_target.month_id: 2026-08,2026-09,2026-10,2026-11,2026-12,2027-01,2027-02
    sorts: [fact_monthly_target.month_label, fact_state_snapshot.frontline_value desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    series_labels:
      dim_state.state_name: State
      fact_state_snapshot.frontline_value: Frontline target
      fact_state_snapshot.smt_till_aug_value: SMT Trained till Aug'26 (actual)
      fact_monthly_target.smt_target: Batches
    row_total: right
    note_state: collapsed
    note_display: hover
    note_text: Batch targets exactly as the Sheet names them. The Sheet continues through Feb'27.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 34
    col: 0
    width: 24
    height: 12
  - name: tg_national_by_month
    title: National SMT targets by month
    model: central_dashboard
    explore: fact_monthly_target
    type: looker_column
    fields: [fact_monthly_target.month_label, fact_monthly_target.smt_target, fact_monthly_target.smt_target_headcount]
    filters:
      fact_monthly_target.month_id: 2026-08,2026-09,2026-10,2026-11,2026-12,2027-01,2027-02
    sorts: [fact_monthly_target.month_label]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_monthly_target.smt_target: '#1D3557'
      fact_monthly_target.smt_target_headcount: '#D97B34'
    y_axes:
    - label: Batches
      orientation: left
      series:
      - id: fact_monthly_target.smt_target
    - label: SMTs (headcount)
      orientation: right
      series:
      - id: fact_monthly_target.smt_target_headcount
    note_state: collapsed
    note_display: hover
    note_text: 'Headcount: Aug and Sep as written in the Sheet; Oct-Feb derived as batches x 35.'
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 46
    col: 0
    width: 24
    height: 7

  # ======================================================================
  # TAB 7 - ROADMAP 2027 (HTML 'Roadmap 2027' tab)
  # ======================================================================
  - name: rm_header
    type: text
    body_text: <b>Building Capacity for March 2027</b> &mdash; State Lead Trainers, State Master Trainers and frontline reach required to complete the Karmayogi Kartavya Karyakram rollout, with what has been achieved so far against each.
    tab_name: targets_roadmap
    row: 53
    col: 0
    width: 24
    height: 2
  - name: rm_slt_required
    title: State Lead Trainers - required
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.slt_required]
    show_single_value_title: true
    single_value_title: State Lead Trainers - required
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 55
    col: 0
    width: 4
    height: 4
  - name: rm_slt_current
    title: State Lead Trainers - current
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.slt_trained]
    show_single_value_title: true
    single_value_title: State Lead Trainers - current
    custom_color_enabled: true
    custom_color: '#707A88'
    show_comparison: false
    note_state: expanded
    note_display: below
    note_text: No SLT-trained figure exists yet in the source Sheet.
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 55
    col: 4
    width: 4
    height: 4
  - name: rm_smt_required
    title: State Master Trainers - required
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_required]
    show_single_value_title: true
    single_value_title: State Master Trainers - required
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 55
    col: 8
    width: 4
    height: 4
  - name: rm_smt_current
    title: State Master Trainers - current
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained, fact_state_snapshot.smt_required]
    show_single_value_title: true
    single_value_title: State Master Trainers - current
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of required
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 55
    col: 12
    width: 4
    height: 4
  - name: rm_frontline_required
    title: Frontline target - March 2027
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.frontline_target]
    show_single_value_title: true
    single_value_title: Frontline target - March 2027
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 55
    col: 16
    width: 4
    height: 4
  - name: rm_frontline_current
    title: Frontline - current
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained, fact_state_snapshot.frontline_target]
    show_single_value_title: true
    single_value_title: Frontline - current
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '#,##0'
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of frontline target
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 55
    col: 20
    width: 4
    height: 4
  - name: rm_timeline_header
    type: text
    body_text: '<b>Timeline</b> &mdash; Aug 2026: SMT target tracking &rarr; Sep 2026: continued trainer expansion &rarr; Mar 2027: frontline target'
    tab_name: targets_roadmap
    row: 59
    col: 0
    width: 24
    height: 1
  - name: rm_timeline_aug
    title: Aug 2026 - States/UTs that achieved the August SMT target
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_achieved, target_tracker.state_count]
    filters:
      target_tracker.month_label: Aug'26
    show_single_value_title: true
    single_value_title: Aug 2026 - States/UTs that achieved the August SMT target
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '0'
    show_comparison: true
    comparison_type: progress
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of all States/UTs
    tab_name: targets_roadmap
    row: 60
    col: 0
    width: 8
    height: 3
  - name: rm_timeline_sep
    title: Sep 2026 - States/UTs on track against the September target
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_achieved, target_tracker.state_count]
    filters:
      target_tracker.month_label: Sep'26
    show_single_value_title: true
    single_value_title: Sep 2026 - States/UTs on track against the September target
    custom_color_enabled: true
    custom_color: '#AD7C25'
    value_format: '0'
    show_comparison: true
    comparison_type: progress
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of all States/UTs
    tab_name: targets_roadmap
    row: 60
    col: 8
    width: 8
    height: 3
  - name: rm_timeline_mar
    title: Mar 2027 - frontline officials to be reached
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.frontline_target]
    show_single_value_title: true
    single_value_title: Mar 2027 - frontline officials to be reached
    custom_color_enabled: true
    custom_color: '#D97B34'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 60
    col: 16
    width: 8
    height: 3
  - name: rm_zone_grid
    title: Regional Requirement - North · South · East · West
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.zone, fact_state_snapshot.state_count, fact_state_snapshot.slt_required, fact_state_snapshot.smt_required, fact_state_snapshot.smt_trained, fact_state_snapshot.pct_smt_requirement, fact_state_snapshot.frontline_target, fact_state_snapshot.one_day_trained, fact_state_snapshot.pct_frontline_reached]
    sorts: [dim_state.zone]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets_roadmap
    row: 63
    col: 0
    width: 24
    height: 7

  # ======================================================================
  # TAB 8 - ASSESSMENTS (Box 9 One-Day and Box 10 SMT, never merged)
  # ======================================================================
  - name: as_header
    type: text
    body_text: '<b>Assessment and analysis</b> &mdash; the two programmes are assessed separately: a different audience and a different instrument, so their numbers are never merged. <b>All scores are DEMO</b> until the assessment feed arrives.'
    tab_name: assessment_export
    row: 0
    col: 0
    width: 24
    height: 2
  - name: as_box9_header
    type: text
    body_text: <b>Box 9 · One-Day participant programme</b> &mdash; baseline survey, day-1 assessment, and the improvement between them
    tab_name: assessment_export
    row: 2
    col: 0
    width: 24
    height: 1
  - name: as9_assessed
    title: One-Day participants assessed
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.participants_assessed]
    filters:
      fact_assessment.programme_type: One-Day
    show_single_value_title: true
    single_value_title: One-Day participants assessed
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 3
    col: 0
    width: 6
    height: 3
  - name: as9_baseline
    title: Baseline survey - average score
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.weighted_baseline_score]
    filters:
      fact_assessment.programme_type: One-Day
    show_single_value_title: true
    single_value_title: Baseline survey - average score
    custom_color_enabled: true
    custom_color: '#707A88'
    value_format: '0.0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 3
    col: 6
    width: 6
    height: 3
  - name: as9_day1
    title: Day-1 assessment - average score
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.weighted_day1_score]
    filters:
      fact_assessment.programme_type: One-Day
    show_single_value_title: true
    single_value_title: Day-1 assessment - average score
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '0.0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 3
    col: 12
    width: 6
    height: 3
  - name: as9_improvement
    title: Baseline vs Day-1 - improvement (points)
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.weighted_improvement]
    filters:
      fact_assessment.programme_type: One-Day
    show_single_value_title: true
    single_value_title: Baseline vs Day-1 - improvement (points)
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: +0.0;-0.0;0.0
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 3
    col: 18
    width: 6
    height: 3
  - name: as9_by_state
    title: Baseline vs Day-1 by State/UT
    model: central_dashboard
    explore: fact_assessment
    type: looker_column
    fields: [dim_state.state_name, fact_assessment.weighted_baseline_score, fact_assessment.weighted_day1_score]
    filters:
      fact_assessment.programme_type: One-Day
    sorts: [fact_assessment.weighted_day1_score desc]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_assessment.weighted_baseline_score: '#D9D5C9'
      fact_assessment.weighted_day1_score: '#1D3557'
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 6
    col: 0
    width: 14
    height: 8
  - name: as9_improvement_by_state
    title: Improvement by State/UT (points)
    model: central_dashboard
    explore: fact_assessment
    type: looker_bar
    fields: [dim_state.state_name, fact_assessment.weighted_improvement]
    filters:
      fact_assessment.programme_type: One-Day
    sorts: [fact_assessment.weighted_improvement desc]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_assessment.weighted_improvement: '#2F7D57'
    hide_legend: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 6
    col: 14
    width: 10
    height: 8
  - name: as9_table
    title: Box 9 detail - One-Day assessment by State/UT
    model: central_dashboard
    explore: fact_assessment
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, fact_assessment.participants_assessed, fact_assessment.weighted_baseline_score, fact_assessment.weighted_day1_score, fact_assessment.weighted_improvement, fact_assessment.data_source]
    filters:
      fact_assessment.programme_type: One-Day
    sorts: [fact_assessment.weighted_improvement desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 14
    col: 0
    width: 24
    height: 7
  - name: as_box10_header
    type: text
    body_text: <b>Box 10 · State Master Trainer programme</b> &mdash; certification outcome of the 2-day programme
    tab_name: assessment_export
    row: 21
    col: 0
    width: 24
    height: 1
  - name: as10_assessed
    title: SMTs assessed
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.participants_assessed]
    filters:
      fact_assessment.programme_type: SMT
    show_single_value_title: true
    single_value_title: SMTs assessed
    custom_color_enabled: true
    custom_color: '#1D3557'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 22
    col: 0
    width: 6
    height: 3
  - name: as10_certified
    title: Certified
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.certified_count]
    filters:
      fact_assessment.programme_type: SMT
    show_single_value_title: true
    single_value_title: Certified
    custom_color_enabled: true
    custom_color: '#2F7D57'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 22
    col: 6
    width: 6
    height: 3
  - name: as10_not_certified
    title: Not certified
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.not_certified_count]
    filters:
      fact_assessment.programme_type: SMT
    show_single_value_title: true
    single_value_title: Not certified
    custom_color_enabled: true
    custom_color: '#B04435'
    value_format: '#,##0'
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 22
    col: 12
    width: 6
    height: 3
  - name: as10_rate
    title: Certification rate
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.certification_rate]
    filters:
      fact_assessment.programme_type: SMT
    show_single_value_title: true
    single_value_title: Certification rate
    custom_color_enabled: true
    custom_color: '#12233B'
    value_format: 0.0%
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 22
    col: 18
    width: 6
    height: 3
  - name: as10_outcome_by_state
    title: SMT certification outcome by State/UT
    model: central_dashboard
    explore: fact_assessment
    type: looker_column
    fields: [dim_state.state_name, fact_assessment.certified_count, fact_assessment.not_certified_count]
    filters:
      fact_assessment.programme_type: SMT
    sorts: [fact_assessment.certified_count desc]
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    legend_position: center
    show_view_names: false
    series_colors:
      fact_assessment.certified_count: '#2F7D57'
      fact_assessment.not_certified_count: '#B04435'
    stacking: normal
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 25
    col: 0
    width: 14
    height: 8
  - name: as10_table
    title: Box 10 detail - SMT assessment by State/UT
    model: central_dashboard
    explore: fact_assessment
    type: looker_grid
    fields: [dim_state.state_name, fact_assessment.participants_assessed, fact_assessment.certified_count, fact_assessment.not_certified_count, fact_assessment.certification_rate, fact_assessment.weighted_day1_score]
    filters:
      fact_assessment.programme_type: SMT
    sorts: [fact_assessment.certification_rate desc]
    limit: 500
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
      batch_date: dim_date.date
    tab_name: assessment_export
    row: 25
    col: 14
    width: 10
    height: 8

  # ======================================================================
  # TAB 9 - FULL DATA EXPORT (Box 11). No filters: every tile returns everything.
  # ======================================================================
  - name: ex_header
    type: text
    body_text: '<b>Full data export</b> &mdash; one button, everything: dashboard menu (&#8942;) &rarr; <b>Download</b> &rarr; CSV gives a zip with one file per tile below. No filter is required first and none applies to this tab. Each tile can also be downloaded on its own, or the dashboard scheduled to an inbox.'
    tab_name: assessment_export
    row: 33
    col: 0
    width: 24
    height: 2
  - name: ex_batch_detail
    title: Every state, district, group, designation and batch
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, dim_state.state_type, dim_district.district_name, dim_group.group_name, dim_designation.designation_name, fact_batch_activity.batch_type, fact_batch_activity.batch_date, fact_batch_activity.implementation_status, fact_batch_activity.data_source, fact_batch_activity.participants_trained, fact_batch_activity.batch_count]
    sorts: [dim_state.state_name, fact_batch_activity.batch_date desc]
    limit: 5000
    total: true
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    show_totals: true
    tab_name: assessment_export
    row: 35
    col: 0
    width: 24
    height: 10
  - name: ex_state_snapshot
    title: Every State/UT - implementation and requirement
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, dim_state.state_type, dim_state.programme_coordinator, fact_state_snapshot.stage, fact_state_snapshot.smt_status, fact_state_snapshot.one_day_status, fact_state_snapshot.smt_value, fact_state_snapshot.smt_batches_value, fact_state_snapshot.one_day_value, fact_state_snapshot.one_day_batches_value, fact_state_snapshot.frontline_value, fact_state_snapshot.slt_required_value, fact_state_snapshot.smt_required_value, fact_state_snapshot.smt_batches_required_value, fact_state_snapshot.smt_till_aug_value, fact_state_snapshot.snapshot_date, fact_state_snapshot.target_snapshot_date]
    sorts: [dim_state.state_name]
    limit: 500
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    tab_name: assessment_export
    row: 45
    col: 0
    width: 24
    height: 8
  - name: ex_monthly_targets
    title: The monthly target sheet - every State x month
    model: central_dashboard
    explore: fact_monthly_target
    type: looker_grid
    fields: [dim_state.state_name, fact_monthly_target.month_label, fact_monthly_target.headcount_basis, fact_monthly_target.smt_target, fact_monthly_target.smt_target_headcount, fact_monthly_target.smt_required, fact_monthly_target.slt_required, fact_monthly_target.frontline_target, fact_monthly_target.smt_batches_required, fact_monthly_target.slt_batches_required]
    sorts: [dim_state.state_name, fact_monthly_target.month_label]
    limit: 5000
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    tab_name: assessment_export
    row: 53
    col: 0
    width: 24
    height: 8
  - name: ex_assessments
    title: Both assessment types (demo scores)
    model: central_dashboard
    explore: fact_assessment
    type: looker_grid
    fields: [dim_state.state_name, fact_assessment.programme_type, fact_assessment.assessment_date, fact_assessment.data_source, fact_assessment.participants_assessed, fact_assessment.avg_baseline_score, fact_assessment.avg_day1_score, fact_assessment.certified_count, fact_assessment.not_certified_count]
    sorts: [dim_state.state_name, fact_assessment.programme_type]
    limit: 5000
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    enable_conditional_formatting: false
    header_text_alignment: left
    header_font_size: '12'
    rows_font_size: '12'
    tab_name: assessment_export
    row: 61
    col: 0
    width: 24
    height: 8
