# ============================================================================
# FILE: central_dashboard.dashboard.lookml
# Section B - National Implementation Dashboard (CBC, unrestricted)
# Karmayogi Kartavya Karyakram
#
# Tabs (Looker 26.4+):
#   1 National Overview   - headline numbers, 1.3 crore progress, India map,
#                           State-wise and zone-wise progress
#   2 SMT · One-Day · SLT - progress against requirement, gaps by State,
#                           month-wise activity, group and designation
#   3 State & District    - State record, districts, designations
#   4 Monthly SMT Targets - this month / last month, State x month tracker
#   5 Assessments & Export
#
# Filters: Zone and State / UT (tick boxes). Every tile follows them; with
# nothing ticked, every tile covers all of India.
# Toggle tiles use the custom visualizations kkk_switch_bars and kkk_state_map
# declared in manifest.lkml (they appear once deployed to production).
# Generated by gen_dashboard.py.
# ============================================================================

- dashboard: central_dashboard
  title: National Implementation Dashboard
  description: Capacity Building Commission - Karmayogi Kartavya Karyakram. Every State and UT.
  layout: newspaper
  preferred_viewer: dashboards-next
  refresh: 1 hour
  crossfilter_enabled: true
  enable_viz_full_screen: true
  filters_location_top: true
  embed_style:
    background_color: '#FAF8F3'
    tile_background_color: '#FFFFFF'
    tile_text_color: '#1C2430'
    title_color: '#12233B'
    show_title: true
    text_tile_text_color: '#707A88'
  tabs:
  - name: overview
    label: National Overview
  - name: programmes
    label: SMT · One-Day · SLT
  - name: state
    label: State & District
  - name: targets
    label: Monthly SMT Targets
  - name: assessment_export
    label: Assessments & Export
  filters:
  - name: zone
    title: Zone
    type: field_filter
    default_value: ''
    allow_multiple_values: true
    required: false
    ui_config:
      type: checkboxes
      display: popover
    model: central_dashboard
    explore: state_snapshot
    field: dim_state.zone
  - name: state
    title: State / UT
    type: field_filter
    default_value: ''
    allow_multiple_values: true
    required: false
    ui_config:
      type: checkboxes
      display: popover
    model: central_dashboard
    explore: state_snapshot
    listens_to_filters: [zone]
    field: dim_state.state_name
  elements:

  # ---------------------------------------------------------------- NATIONAL OVERVIEW
  - name: ov_started
    title: States/UTs started
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_started, fact_state_snapshot.state_count]
    show_single_value_title: true
    single_value_title: States/UTs started
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#12233B"
    value_format: "0"
    show_comparison: true
    comparison_type: progress
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of total
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 0
    col: 0
    width: 6
    height: 4
  - name: ov_smt
    title: SMTs trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained, fact_state_snapshot.smt_batches]
    show_single_value_title: true
    single_value_title: SMTs trained
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#AD7C25"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: batches
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 0
    col: 6
    width: 6
    height: 4
  - name: ov_one_day
    title: One-Day trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained, fact_state_snapshot.one_day_batches]
    show_single_value_title: true
    single_value_title: One-Day trained
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: batches
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 0
    col: 12
    width: 6
    height: 4
  - name: ov_not_started
    title: States/UTs yet to start
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.states_not_started]
    show_single_value_title: true
    single_value_title: States/UTs yet to start
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#B04435"
    value_format: "0"
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 0
    col: 18
    width: 6
    height: 4
  - name: ov_target
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.programme_progress, fact_state_snapshot.programme_still_to_reach]
    hidden_fields: [fact_state_snapshot.programme_still_to_reach]
    show_single_value_title: false
    title_hidden: true
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 4
    col: 0
    width: 24
    height: 3
  - name: ov_map
    title: India - click a State/UT to filter the dashboard
    model: central_dashboard
    explore: state_snapshot
    type: "central_dashboard::kkk_state_map"
    fields: [dim_state.state_name, fact_state_snapshot.stage_code, fact_state_snapshot.smt_trained, fact_state_snapshot.one_day_trained, fact_state_snapshot.slt_required]
    sorts: [dim_state.state_name]
    limit: 500
    default_measure: stage_code
    categories: "stage_code=1:Yet to start:#B04435|2:SMT completed:#AD7C25|3:One-Day completed:#2F7D57"
    labels: stage_code=Status;smt_trained=SMTs trained;one_day_trained=One-Day trained;slt_required=SLTs required
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557"
    show_labels: true
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 7
    col: 0
    width: 15
    height: 17
  - name: ov_yet_to_start
    title: Yet to start - follow up
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, dim_state.state_type]
    sorts: [dim_state.zone, dim_state.state_name]
    limit: 5000
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    series_labels:
      dim_state.state_name: State / UT
      dim_state.zone: Zone
      dim_state.state_type: Type
    filters:
      fact_state_snapshot.has_started: No
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 7
    col: 15
    width: 9
    height: 17
  - name: ov_statewise
    title: State-wise progress
    model: central_dashboard
    explore: state_snapshot
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_state.state_name, fact_state_snapshot.one_day_trained, fact_state_snapshot.smt_trained, fact_state_snapshot.one_day_batches, fact_state_snapshot.smt_batches]
    sorts: [fact_state_snapshot.one_day_trained desc]
    limit: 500
    orientation: horizontal
    bar_order: value
    hide_zero: true
    top_n: 0
    show_total: true
    default_measure: ""
    labels: one_day_trained=One-Day trained;smt_trained=SMTs trained;one_day_batches=One-Day batches;smt_batches=SMT batches
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 24
    col: 0
    width: 14
    height: 13
  - name: ov_zone
    title: Zone comparison
    model: central_dashboard
    explore: state_snapshot
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_state.zone, fact_state_snapshot.smt_trained, fact_state_snapshot.one_day_trained, fact_state_snapshot.smt_batches, fact_state_snapshot.one_day_batches, fact_state_snapshot.states_started]
    sorts: [dim_state.zone]
    limit: 500
    orientation: vertical
    bar_order: data
    hide_zero: false
    top_n: 0
    show_total: true
    default_measure: ""
    labels: smt_trained=SMTs;one_day_trained=One-Day;smt_batches=SMT batches;one_day_batches=One-Day batches;states_started=States started
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557,states_started:#12233B"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: overview
    row: 24
    col: 14
    width: 10
    height: 13

  # ---------------------------------------------------------------- SMT · ONE-DAY · SLT
  - name: pg_smt
    title: SMTs trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_trained, fact_state_snapshot.smt_required]
    show_single_value_title: true
    single_value_title: SMTs trained
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#AD7C25"
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of required
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 0
    col: 0
    width: 4
    height: 4
  - name: pg_smt_batches
    title: SMT batches
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.smt_batches, fact_state_snapshot.smt_batches_required]
    show_single_value_title: true
    single_value_title: SMT batches
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#AD7C25"
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of required
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 0
    col: 4
    width: 4
    height: 4
  - name: pg_one_day
    title: One-Day trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_trained, fact_state_snapshot.frontline_target]
    show_single_value_title: true
    single_value_title: One-Day trained
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    show_comparison: true
    comparison_type: progress_percentage
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of State targets
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 0
    col: 8
    width: 4
    height: 4
  - name: pg_one_day_batches
    title: One-Day batches
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.one_day_batches, fact_state_snapshot.states_one_day]
    show_single_value_title: true
    single_value_title: One-Day batches
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: States/UTs active
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 0
    col: 12
    width: 4
    height: 4
  - name: pg_slt_required
    title: SLTs required
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.slt_required, fact_state_snapshot.slt_batches_required]
    show_single_value_title: true
    single_value_title: SLTs required
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#1D3557"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: batches needed
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 0
    col: 16
    width: 4
    height: 4
  - name: pg_slt_trained
    title: SLTs trained
    model: central_dashboard
    explore: state_snapshot
    type: single_value
    fields: [fact_state_snapshot.slt_trained]
    show_single_value_title: true
    single_value_title: SLTs trained
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#707A88"
    show_comparison: false
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 0
    col: 20
    width: 4
    height: 4
  - name: pg_gap
    title: Still to go - by State/UT (March 2027 requirement)
    model: central_dashboard
    explore: state_snapshot
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_state.state_name, fact_state_snapshot.smt_still_required, fact_state_snapshot.frontline_still_to_reach, fact_state_snapshot.slt_required]
    sorts: [fact_state_snapshot.smt_still_required desc]
    limit: 500
    orientation: horizontal
    bar_order: value
    hide_zero: true
    top_n: 0
    show_total: true
    default_measure: ""
    labels: smt_still_required=SMTs still to train;frontline_still_to_reach=Frontline still to reach;slt_required=SLTs required
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 4
    col: 0
    width: 12
    height: 14
  - name: pg_monthly
    title: Month-wise activity
    model: central_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_date.month_label, fact_batch_activity.smt_trained, fact_batch_activity.smt_batches, fact_batch_activity.one_day_trained, fact_batch_activity.one_day_batches]
    sorts: [dim_date.month_label]
    limit: 500
    orientation: vertical
    bar_order: data
    hide_zero: false
    top_n: 0
    show_total: true
    default_measure: ""
    labels: smt_trained=SMTs trained;smt_batches=SMT batches;one_day_trained=One-Day trained;one_day_batches=One-Day batches
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 4
    col: 12
    width: 12
    height: 14
  - name: pg_group
    title: By service group
    model: central_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_group.group_name, fact_batch_activity.one_day_trained, fact_batch_activity.smt_trained]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 500
    orientation: horizontal
    bar_order: value
    hide_zero: true
    top_n: 0
    show_total: true
    default_measure: ""
    labels: one_day_trained=One-Day trained;smt_trained=SMTs trained
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 18
    col: 0
    width: 12
    height: 11
  - name: pg_designation
    title: By designation
    model: central_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_designation.designation_name, fact_batch_activity.one_day_trained, fact_batch_activity.smt_trained]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 500
    orientation: horizontal
    bar_order: value
    hide_zero: true
    top_n: 0
    show_total: true
    default_measure: ""
    labels: one_day_trained=One-Day trained;smt_trained=SMTs trained
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: programmes
    row: 18
    col: 12
    width: 12
    height: 11

  # ---------------------------------------------------------------- STATE & DISTRICT
  - name: st_hint
    type: text
    title_text: ""
    body_text: "Tick one or more States/UTs in the <b>State / UT</b> filter, or click a State on the India map. With nothing ticked, this tab lists every State and UT."
    tab_name: state
    row: 0
    col: 0
    width: 24
    height: 1
  - name: st_record
    title: State record
    model: central_dashboard
    explore: state_snapshot
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, fact_state_snapshot.stage, fact_state_snapshot.smt_trained, fact_state_snapshot.smt_required, fact_state_snapshot.pct_smt_requirement, fact_state_snapshot.one_day_trained, fact_state_snapshot.frontline_target, fact_state_snapshot.pct_frontline_reached, fact_state_snapshot.slt_required]
    sorts: [dim_state.zone, dim_state.state_name]
    limit: 5000
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    total: true
    show_totals: true
    series_labels:
      dim_state.state_name: State / UT
      dim_state.zone: Zone
      fact_state_snapshot.stage: Status
      fact_state_snapshot.smt_trained: SMTs trained
      fact_state_snapshot.smt_required: SMTs required
      fact_state_snapshot.pct_smt_requirement: SMT req. met
      fact_state_snapshot.one_day_trained: One-Day trained
      fact_state_snapshot.frontline_target: Frontline target
      fact_state_snapshot.pct_frontline_reached: Frontline reached
      fact_state_snapshot.slt_required: SLTs required
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: state
    row: 1
    col: 0
    width: 24
    height: 10
  - name: st_districts
    title: By district
    model: central_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_district.district_name, fact_batch_activity.one_day_trained, fact_batch_activity.smt_trained, fact_batch_activity.one_day_batches]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 500
    orientation: horizontal
    bar_order: value
    hide_zero: true
    top_n: 0
    show_total: true
    default_measure: ""
    labels: one_day_trained=One-Day trained;smt_trained=SMTs trained;one_day_batches=One-Day batches
    colors: "smt:#AD7C25,one_day:#2F7D57,frontline:#2F7D57,slt:#1D3557"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: state
    row: 11
    col: 0
    width: 12
    height: 14
  - name: st_designations
    title: By designation
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_designation.designation_name, dim_group.group_name, fact_batch_activity.one_day_trained, fact_batch_activity.smt_trained]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 5000
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    total: true
    show_totals: true
    series_labels:
      dim_designation.designation_name: Designation
      dim_group.group_name: Group
      fact_batch_activity.one_day_trained: One-Day trained
      fact_batch_activity.smt_trained: SMTs trained
    series_cell_visualizations:
      fact_batch_activity.one_day_trained:
        is_active: true
        palette:
          palette_id: kkk-green
          collection_id: custom
          custom_colors: ["#2F7D57", "#2F7D57"]
      fact_batch_activity.smt_trained:
        is_active: true
        palette:
          palette_id: kkk-amber
          collection_id: custom
          custom_colors: ["#AD7C25", "#AD7C25"]
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: state
    row: 11
    col: 12
    width: 12
    height: 14

  # ---------------------------------------------------------------- MONTHLY SMT TARGETS
  - name: tg_achieved
    title: Target achieved - this month
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_achieved, target_tracker.states_applicable]
    show_single_value_title: true
    single_value_title: Target achieved - this month
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    value_format: "0"
    show_comparison: true
    filters:
      target_tracker.month_window: This month
    comparison_type: progress
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: of States/UTs with a target
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets
    row: 0
    col: 0
    width: 6
    height: 4
  - name: tg_in_progress
    title: In progress - this month
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_in_progress]
    show_single_value_title: true
    single_value_title: In progress - this month
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#AD7C25"
    value_format: "0"
    show_comparison: false
    filters:
      target_tracker.month_window: This month
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets
    row: 0
    col: 6
    width: 6
    height: 4
  - name: tg_missed
    title: Missed - last month
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.states_not_achieved]
    show_single_value_title: true
    single_value_title: Missed - last month
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#B04435"
    value_format: "0"
    show_comparison: false
    filters:
      target_tracker.month_window: Last month
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets
    row: 0
    col: 12
    width: 6
    height: 4
  - name: tg_batches
    title: SMT batch target - this month
    model: central_dashboard
    explore: target_tracker
    type: single_value
    fields: [target_tracker.target_batches, target_tracker.target_smts]
    show_single_value_title: true
    single_value_title: SMT batch target - this month
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#1D3557"
    show_comparison: true
    filters:
      target_tracker.month_window: This month
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: SMTs
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets
    row: 0
    col: 18
    width: 6
    height: 4
  - name: tg_matrix
    title: "Target tracker - every State/UT, every month"
    model: central_dashboard
    explore: target_tracker
    type: looker_grid
    fields: [dim_state.state_name, target_tracker.smt_trained_value, target_tracker.month_label, target_tracker.status_cell]
    sorts: [target_tracker.month_label, dim_state.state_name]
    limit: 5000
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    series_labels:
      dim_state.state_name: State / UT
      target_tracker.smt_trained_value: SMTs trained so far
      target_tracker.status_cell: Status
    pivots: [target_tracker.month_label]
    filters:
      target_tracker.target_smts_value: ">0"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets
    row: 4
    col: 0
    width: 24
    height: 15
  - name: tg_by_month
    title: National SMT targets by month
    model: central_dashboard
    explore: fact_monthly_target
    type: looker_column
    fields: [fact_monthly_target.month_label, fact_monthly_target.smt_target, fact_monthly_target.smt_target_headcount]
    filters:
      fact_monthly_target.month_id: "2026-08,2026-09,2026-10,2026-11,2026-12,2027-01,2027-02"
    sorts: [fact_monthly_target.month_label]
    limit: 50
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_view_names: false
    legend_position: center
    series_colors:
      fact_monthly_target.smt_target: "#1D3557"
      fact_monthly_target.smt_target_headcount: "#D97B34"
    series_labels:
      fact_monthly_target.smt_target: Batch target
      fact_monthly_target.smt_target_headcount: SMT target (headcount)
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: targets
    row: 19
    col: 0
    width: 24
    height: 8
    y_axes:
    - label: Batches
      orientation: left
      series:
      - id: fact_monthly_target.smt_target
    - label: SMTs
      orientation: right
      series:
      - id: fact_monthly_target.smt_target_headcount

  # ---------------------------------------------------------------- ASSESSMENTS & EXPORT
  - name: as_od_head
    type: text
    title_text: ""
    body_text: "<b style=\"color:#12233B;font-size:15px;\">One-Day participant programme</b> &mdash; baseline survey, day-1 assessment and the improvement between them"
    tab_name: assessment_export
    row: 0
    col: 0
    width: 24
    height: 1
  - name: as_od_assessed
    title: Participants assessed
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.participants_assessed]
    show_single_value_title: true
    single_value_title: Participants assessed
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#12233B"
    show_comparison: false
    filters:
      fact_assessment.programme_type: One-Day
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 1
    col: 0
    width: 6
    height: 4
  - name: as_od_baseline
    title: Baseline score
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.weighted_baseline_score]
    show_single_value_title: true
    single_value_title: Baseline score
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#707A88"
    show_comparison: false
    filters:
      fact_assessment.programme_type: One-Day
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 1
    col: 6
    width: 6
    height: 4
  - name: as_od_day1
    title: Day-1 score
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.weighted_day1_score]
    show_single_value_title: true
    single_value_title: Day-1 score
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#1D3557"
    show_comparison: false
    filters:
      fact_assessment.programme_type: One-Day
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 1
    col: 12
    width: 6
    height: 4
  - name: as_od_improvement
    title: Improvement (points)
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.weighted_improvement]
    show_single_value_title: true
    single_value_title: Improvement (points)
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    show_comparison: false
    filters:
      fact_assessment.programme_type: One-Day
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 1
    col: 18
    width: 6
    height: 4
  - name: as_od_by_state
    title: Baseline vs Day-1 by State/UT
    model: central_dashboard
    explore: fact_assessment
    type: looker_column
    fields: [dim_state.state_name, fact_assessment.weighted_baseline_score, fact_assessment.weighted_day1_score]
    filters:
      fact_assessment.programme_type: One-Day
    sorts: [fact_assessment.weighted_day1_score desc]
    limit: 50
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_view_names: false
    legend_position: center
    series_colors:
      fact_assessment.weighted_baseline_score: "#D9D5C9"
      fact_assessment.weighted_day1_score: "#1D3557"
    series_labels:
      fact_assessment.weighted_baseline_score: Baseline
      fact_assessment.weighted_day1_score: Day-1
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 5
    col: 0
    width: 24
    height: 8
  - name: as_smt_head
    type: text
    title_text: ""
    body_text: "<b style=\"color:#12233B;font-size:15px;\">State Master Trainer assessment</b> &mdash; certification outcome"
    tab_name: assessment_export
    row: 13
    col: 0
    width: 24
    height: 1
  - name: as_smt_assessed
    title: SMTs assessed
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.participants_assessed]
    show_single_value_title: true
    single_value_title: SMTs assessed
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#12233B"
    show_comparison: false
    filters:
      fact_assessment.programme_type: SMT
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 14
    col: 0
    width: 8
    height: 4
  - name: as_smt_certified
    title: Certified
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.certified_count, fact_assessment.certification_rate]
    show_single_value_title: true
    single_value_title: Certified
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    show_comparison: true
    filters:
      fact_assessment.programme_type: SMT
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: certification rate
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 14
    col: 8
    width: 8
    height: 4
  - name: as_smt_not
    title: Not certified
    model: central_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.not_certified_count]
    show_single_value_title: true
    single_value_title: Not certified
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#B04435"
    show_comparison: false
    filters:
      fact_assessment.programme_type: SMT
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 14
    col: 16
    width: 8
    height: 4
  - name: as_smt_by_state
    title: Certification outcome by State/UT
    model: central_dashboard
    explore: fact_assessment
    type: looker_column
    fields: [dim_state.state_name, fact_assessment.certified_count, fact_assessment.not_certified_count]
    filters:
      fact_assessment.programme_type: SMT
    sorts: [fact_assessment.certified_count desc]
    limit: 50
    stacking: normal
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_view_names: false
    legend_position: center
    series_colors:
      fact_assessment.certified_count: "#2F7D57"
      fact_assessment.not_certified_count: "#B04435"
    series_labels:
      fact_assessment.certified_count: Certified
      fact_assessment.not_certified_count: Not certified
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 18
    col: 0
    width: 24
    height: 8
  - name: ex_head
    type: text
    title_text: ""
    body_text: "<b style=\"color:#12233B;font-size:15px;\">Export</b> &mdash; ⋮ on a tile &gt; Download for that table (Excel or CSV), or ⋮ on the dashboard &gt; Download for everything. Exports follow the Zone and State / UT filters."
    tab_name: assessment_export
    row: 26
    col: 0
    width: 24
    height: 1
  - name: ex_batches
    title: "Batch-level data - State, district, group, designation"
    model: central_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_state.state_name, dim_state.zone, dim_district.district_name, dim_group.group_name, dim_designation.designation_name, fact_batch_activity.batch_type, fact_batch_activity.batch_date, fact_batch_activity.implementation_status, fact_batch_activity.participants_trained, fact_batch_activity.batch_count]
    sorts: [dim_state.state_name, fact_batch_activity.batch_date desc]
    limit: 5000
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    total: true
    show_totals: true
    series_labels:
      dim_state.state_name: State / UT
      dim_state.zone: Zone
      dim_district.district_name: District
      dim_group.group_name: Group
      dim_designation.designation_name: Designation
      fact_batch_activity.batch_type: Programme
      fact_batch_activity.batch_date: Batch date
      fact_batch_activity.implementation_status: Status
      fact_batch_activity.participants_trained: Participants
      fact_batch_activity.batch_count: Batches
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 27
    col: 0
    width: 24
    height: 10
  - name: ex_targets
    title: Monthly target sheet - every State/UT and month
    model: central_dashboard
    explore: fact_monthly_target
    type: looker_grid
    fields: [dim_state.state_name, fact_monthly_target.month_label, fact_monthly_target.smt_target, fact_monthly_target.smt_target_headcount, fact_monthly_target.smt_required, fact_monthly_target.slt_required, fact_monthly_target.frontline_target]
    sorts: [dim_state.state_name, fact_monthly_target.month_label]
    limit: 5000
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    series_labels:
      dim_state.state_name: State / UT
      fact_monthly_target.month_label: Month
      fact_monthly_target.smt_target: SMT batch target
      fact_monthly_target.smt_target_headcount: SMT target (headcount)
      fact_monthly_target.smt_required: SMTs required
      fact_monthly_target.slt_required: SLTs required
      fact_monthly_target.frontline_target: Frontline target
    filters:
      fact_monthly_target.month_id: "2026-08,2026-09,2026-10,2026-11,2026-12,2027-01,2027-02"
    listen:
      zone: dim_state.zone
      state: dim_state.state_name
    tab_name: assessment_export
    row: 37
    col: 0
    width: 24
    height: 8
