# ============================================================================
# FILE: state_dashboard.dashboard.lookml
# Section A - State Implementation Dashboard - Karmayogi Kartavya Karyakram
#
# Tabs (Looker 26.4+):
#   1 State overview        - headline numbers, district map, district table
#                             (State total row + per-district Download links)
#   2 1-Day programme       - activity by month, service group, designation,
#                             and the 1-Day assessment (baseline vs day-1)
#   3 SMT & SLT             - requirement to Mar '27, monthly target vs actual,
#                             districts, designations, certification
#   4 Download data         - full state data for Excel
#
# Filters: State / UT (one State, required) and District (tick boxes).
# Toggle tiles use kkk_switch_bars; the map uses kkk_district_map (manifest).
# Generated by gen_state_dashboard.py.
# ============================================================================

- dashboard: state_dashboard
  title: State Implementation Dashboard
  description: Karmayogi Kartavya Karyakram - the selected State / UT's own view of the rollout.
  layout: newspaper
  preferred_viewer: dashboards-next
  refresh: 1 hour
  crossfilter_enabled: true
  enable_viz_full_screen: true
  filters_location_top: true
  embed_style:
    background_color: '#FAF8F3'
    tile_background_color: '#FFFFFF'
    tile_text_color: '#1C2430'
    title_color: '#12233B'
    show_title: true
    text_tile_text_color: '#707A88'
  tabs:
  - name: overview
    label: State overview
  - name: one_day
    label: 1-Day programme
  - name: smt_slt
    label: SMT & SLT
  - name: download
    label: Download data
  filters:
  - name: state
    title: State / UT
    type: field_filter
    default_value: Odisha
    allow_multiple_values: false
    required: true
    ui_config:
      type: dropdown_menu
      display: inline
    model: state_dashboard
    explore: fact_batch_activity
    field: dim_state.state_name
  - name: district
    title: District
    type: field_filter
    default_value: ''
    allow_multiple_values: true
    required: false
    ui_config:
      type: checkboxes
      display: popover
    model: state_dashboard
    explore: fact_batch_activity
    listens_to_filters: [state]
    field: district_map.district_label
  elements:

  # ---------------------------------------------------------------- STATE OVERVIEW
  - name: ov_slt
    title: Total SLT
    model: state_dashboard
    explore: fact_batch_activity
    type: single_value
    fields: [fact_batch_activity.slt_certified]
    show_single_value_title: true
    single_value_title: Total SLT
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#707A88"
    show_comparison: false
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: overview
    row: 0
    col: 0
    width: 6
    height: 4
  - name: ov_smt
    title: Total SMTs
    model: state_dashboard
    explore: fact_batch_activity
    type: single_value
    fields: [fact_batch_activity.smt_trained, fact_batch_activity.smt_batches]
    show_single_value_title: true
    single_value_title: Total SMTs
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#AD7C25"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: 2-day batches
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: overview
    row: 0
    col: 6
    width: 6
    height: 4
  - name: ov_one_day
    title: 1-Day trained
    model: state_dashboard
    explore: fact_batch_activity
    type: single_value
    fields: [fact_batch_activity.one_day_trained, fact_batch_activity.districts_with_one_day]
    show_single_value_title: true
    single_value_title: 1-Day trained
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: districts reached
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: overview
    row: 0
    col: 12
    width: 6
    height: 4
  - name: ov_batches
    title: Total batches
    model: state_dashboard
    explore: fact_batch_activity
    type: single_value
    fields: [fact_batch_activity.one_day_batches, fact_batch_activity.avg_one_day_per_batch]
    show_single_value_title: true
    single_value_title: Total batches
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#D97B34"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: per batch
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: overview
    row: 0
    col: 18
    width: 6
    height: 4
  - name: ov_map
    title: District map - click a district to filter
    model: state_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_district_map"
    fields: [dim_state.state_name, district_map.map_key, fact_batch_activity.one_day_trained, fact_batch_activity.smt_trained, fact_batch_activity.one_day_batches]
    sorts: [district_map.map_key]
    limit: 1000
    default_measure: fact_batch_activity.one_day_trained
    color_low: "#DDEBE1"
    color_high: "#2F7D57"
    no_data_color: "#EEEAE0"
    show_labels: true
    label_mode: name_value
    show_metric_buttons: true
    show_notes: false
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: overview
    row: 4
    col: 0
    width: 14
    height: 15
  - name: ov_districts
    title: District-wise (bottom row = State total)
    model: state_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [district_map.district_label, fact_batch_activity.smt_trained, fact_batch_activity.one_day_batches, fact_batch_activity.one_day_trained, district_map.district_download]
    sorts: [fact_batch_activity.one_day_trained desc, fact_batch_activity.smt_trained desc]
    limit: 5000
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    total: true
    show_totals: true
    series_labels:
      district_map.district_label: District
      fact_batch_activity.smt_trained: SMTs
      fact_batch_activity.one_day_batches: Batches
      fact_batch_activity.one_day_trained: 1-Day trained
      district_map.district_download: Download
    series_cell_visualizations:
      fact_batch_activity.one_day_trained:
        is_active: true
        palette:
          palette_id: kkk-green
          collection_id: custom
          custom_colors: ["#2F7D57", "#2F7D57"]
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: overview
    row: 4
    col: 14
    width: 10
    height: 15

  # ---------------------------------------------------------------- 1-DAY PROGRAMME
  - name: od_trend
    title: Activity by month
    model: state_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_date.month_label, fact_batch_activity.one_day_trained, fact_batch_activity.one_day_batches]
    sorts: [dim_date.month_label]
    limit: 500
    filters:
      fact_batch_activity.batch_type: One-Day
    orientation: vertical
    bar_order: data
    hide_zero: false
    top_n: 0
    show_total: true
    default_measure: ""
    labels: one_day_trained=1-Day trained;one_day_batches=Batches
    colors: "smt:#AD7C25,one_day:#2F7D57,designations:#1D3557,batches:#D97B34"
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: one_day
    row: 0
    col: 0
    width: 14
    height: 11
  - name: od_group
    title: By service group
    model: state_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_switch_bars"
    fields: [dim_group.group_name, fact_batch_activity.one_day_trained, fact_batch_activity.designations_trained]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 500
    filters:
      fact_batch_activity.batch_type: One-Day
    orientation: horizontal
    bar_order: value
    hide_zero: true
    top_n: 0
    show_total: true
    default_measure: ""
    labels: one_day_trained=1-Day trained;designations_trained=Designations
    colors: "smt:#AD7C25,one_day:#2F7D57,designations:#1D3557,batches:#D97B34"
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: one_day
    row: 0
    col: 14
    width: 10
    height: 11
  - name: od_designation
    title: By designation
    model: state_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_designation.designation_name, dim_group.group_name, fact_batch_activity.one_day_trained, fact_batch_activity.one_day_batches]
    sorts: [fact_batch_activity.one_day_trained desc]
    limit: 5000
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    total: true
    show_totals: true
    series_labels:
      dim_designation.designation_name: Designation
      dim_group.group_name: Service group
      fact_batch_activity.one_day_trained: 1-Day trained
      fact_batch_activity.one_day_batches: Batches
    filters:
      fact_batch_activity.batch_type: One-Day
      fact_batch_activity.one_day_trained: ">0"
    series_cell_visualizations:
      fact_batch_activity.one_day_trained:
        is_active: true
        palette:
          palette_id: kkk-green
          collection_id: custom
          custom_colors: ["#2F7D57", "#2F7D57"]
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: one_day
    row: 11
    col: 0
    width: 24
    height: 11
  - name: as_head
    type: text
    title_text: ""
    body_text: "<b style=\"color:#12233B;font-size:15px;\">Assessment</b> &mdash; baseline survey, day-1 assessment and the improvement between them"
    tab_name: one_day
    row: 22
    col: 0
    width: 24
    height: 1
  - name: as_participants
    title: Participants assessed
    model: state_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.participants_assessed]
    show_single_value_title: true
    single_value_title: Participants assessed
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#12233B"
    show_comparison: false
    filters:
      fact_assessment.programme_type: One-Day
    listen:
      state: dim_state.state_name
    tab_name: one_day
    row: 23
    col: 0
    width: 6
    height: 4
  - name: as_baseline
    title: Baseline score
    model: state_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.avg_baseline_score]
    show_single_value_title: true
    single_value_title: Baseline score
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#707A88"
    value_format: "0.0"
    show_comparison: false
    filters:
      fact_assessment.programme_type: One-Day
    listen:
      state: dim_state.state_name
    tab_name: one_day
    row: 23
    col: 6
    width: 6
    height: 4
  - name: as_day1
    title: Day-1 score
    model: state_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.avg_day1_score]
    show_single_value_title: true
    single_value_title: Day-1 score
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#1D3557"
    value_format: "0.0"
    show_comparison: false
    filters:
      fact_assessment.programme_type: One-Day
    listen:
      state: dim_state.state_name
    tab_name: one_day
    row: 23
    col: 12
    width: 6
    height: 4
  - name: as_improvement
    title: Improvement (points)
    model: state_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.avg_improvement, fact_assessment.improvement_pct]
    show_single_value_title: true
    single_value_title: Improvement (points)
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    value_format: +0.0;-0.0;0.0
    show_comparison: true
    filters:
      fact_assessment.programme_type: One-Day
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: over baseline
    listen:
      state: dim_state.state_name
    tab_name: one_day
    row: 23
    col: 18
    width: 6
    height: 4
  - name: as_chart
    title: Baseline vs Day-1 by assessment date
    model: state_dashboard
    explore: fact_assessment
    type: looker_column
    fields: [fact_assessment.assessment_date, fact_assessment.avg_baseline_score, fact_assessment.avg_day1_score]
    filters:
      fact_assessment.programme_type: One-Day
    sorts: [fact_assessment.assessment_date]
    limit: 100
    listen:
      state: dim_state.state_name
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_view_names: false
    legend_position: center
    series_colors:
      fact_assessment.avg_baseline_score: "#D9D5C9"
      fact_assessment.avg_day1_score: "#1D3557"
    series_labels:
      fact_assessment.avg_baseline_score: Baseline
      fact_assessment.avg_day1_score: Day-1
    tab_name: one_day
    row: 27
    col: 0
    width: 24
    height: 8

  # ---------------------------------------------------------------- SMT & SLT
  - name: smt_required
    title: "SMTs required by Mar '27"
    model: state_dashboard
    explore: fact_monthly_target
    type: single_value
    fields: [fact_monthly_target.smt_required, fact_monthly_target.smt_batches_required]
    show_single_value_title: true
    single_value_title: "SMTs required by Mar '27"
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#AD7C25"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: batches
    listen:
      state: dim_state.state_name
    tab_name: smt_slt
    row: 0
    col: 0
    width: 4
    height: 4
  - name: smt_met
    title: Requirement met
    model: state_dashboard
    explore: fact_monthly_target
    type: single_value
    fields: [fact_monthly_target.pct_smt_certified, fact_monthly_target.smt_outstanding]
    show_single_value_title: true
    single_value_title: Requirement met
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#2F7D57"
    value_format: "0.0\"%\""
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: still to train
    listen:
      state: dim_state.state_name
    tab_name: smt_slt
    row: 0
    col: 4
    width: 4
    height: 4
  - name: smt_certified
    title: SMTs certified
    model: state_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.certified_count, fact_assessment.certification_rate]
    show_single_value_title: true
    single_value_title: SMTs certified
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#1D3557"
    show_comparison: true
    filters:
      fact_assessment.programme_type: SMT
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: pass rate
    listen:
      state: dim_state.state_name
    tab_name: smt_slt
    row: 0
    col: 8
    width: 4
    height: 4
  - name: slt_required
    title: "SLTs required by Mar '27"
    model: state_dashboard
    explore: fact_monthly_target
    type: single_value
    fields: [fact_monthly_target.slt_required, fact_monthly_target.slt_batches_required]
    show_single_value_title: true
    single_value_title: "SLTs required by Mar '27"
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#1D3557"
    show_comparison: true
    comparison_type: value
    comparison_reverse_colors: false
    show_comparison_label: true
    comparison_label: batches
    listen:
      state: dim_state.state_name
    tab_name: smt_slt
    row: 0
    col: 12
    width: 4
    height: 4
  - name: slt_trained
    title: SLTs trained
    model: state_dashboard
    explore: fact_batch_activity
    type: single_value
    fields: [fact_batch_activity.slt_certified]
    show_single_value_title: true
    single_value_title: SLTs trained
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#707A88"
    show_comparison: false
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: smt_slt
    row: 0
    col: 16
    width: 4
    height: 4
  - name: smt_not_certified
    title: SMTs not certified
    model: state_dashboard
    explore: fact_assessment
    type: single_value
    fields: [fact_assessment.not_certified_count]
    show_single_value_title: true
    single_value_title: SMTs not certified
    title_hidden: true
    custom_color_enabled: true
    custom_color: "#B04435"
    show_comparison: false
    filters:
      fact_assessment.programme_type: SMT
    listen:
      state: dim_state.state_name
    tab_name: smt_slt
    row: 0
    col: 20
    width: 4
    height: 4
  - name: smt_target_vs_actual
    title: Monthly SMT target vs actual
    model: state_dashboard
    explore: fact_monthly_target
    type: looker_column
    fields: [dim_month.month_label, dim_month.month_id, fact_monthly_target.smt_target, fact_monthly_target.smt_actual]
    hidden_fields: [dim_month.month_id]
    sorts: [dim_month.month_id]
    limit: 24
    listen:
      state: dim_state.state_name
    show_value_labels: true
    x_axis_gridlines: false
    y_axis_gridlines: true
    show_view_names: false
    legend_position: center
    series_colors:
      fact_monthly_target.smt_target: "#1D3557"
      fact_monthly_target.smt_actual: "#D97B34"
    series_labels:
      fact_monthly_target.smt_target: Target
      fact_monthly_target.smt_actual: Actual
    tab_name: smt_slt
    row: 4
    col: 0
    width: 14
    height: 11
  - name: smt_district
    title: By district
    model: state_dashboard
    explore: fact_batch_activity
    type: "central_dashboard::kkk_switch_bars"
    fields: [district_map.district_label, fact_batch_activity.smt_trained, fact_batch_activity.smt_batches]
    sorts: [fact_batch_activity.smt_trained desc]
    limit: 500
    orientation: horizontal
    bar_order: value
    hide_zero: true
    top_n: 0
    show_total: true
    default_measure: ""
    labels: smt_trained=SMTs;smt_batches=2-day batches
    colors: "smt_trained:#AD7C25,smt_batches:#D97B34"
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: smt_slt
    row: 4
    col: 14
    width: 10
    height: 11
  - name: smt_designation
    title: By designation
    model: state_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_designation.designation_name, dim_group.group_name, fact_batch_activity.smt_trained, fact_batch_activity.smt_batches]
    sorts: [fact_batch_activity.smt_trained desc]
    limit: 5000
    show_view_names: false
    show_row_numbers: true
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    total: true
    show_totals: true
    series_labels:
      dim_designation.designation_name: Designation
      dim_group.group_name: Service group
      fact_batch_activity.smt_trained: SMTs
      fact_batch_activity.smt_batches: 2-day batches
    filters:
      fact_batch_activity.smt_trained: ">0"
    series_cell_visualizations:
      fact_batch_activity.smt_trained:
        is_active: true
        palette:
          palette_id: kkk-amber
          collection_id: custom
          custom_colors: ["#AD7C25", "#AD7C25"]
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: smt_slt
    row: 15
    col: 0
    width: 24
    height: 10

  # ---------------------------------------------------------------- DOWNLOAD DATA
  - name: dl_head
    type: text
    title_text: ""
    body_text: "<b style=\"color:#12233B;font-size:15px;\">Download</b> &mdash; ⋮ on <b>Full state data</b> &gt; Download &gt; Excel &gt; All results. One district: use its Download link on the State overview tab."
    tab_name: download
    row: 0
    col: 0
    width: 24
    height: 1
  - name: dl_explore
    model: state_dashboard
    explore: fact_batch_activity
    type: single_value
    fields: [dim_state.download_full_state_data]
    sorts: [dim_state.download_full_state_data]
    limit: 1
    show_single_value_title: false
    title_hidden: true
    show_comparison: false
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: download
    row: 1
    col: 0
    width: 24
    height: 2
  - name: dl_full
    title: Full state data
    model: state_dashboard
    explore: fact_batch_activity
    type: looker_grid
    fields: [dim_state.state_name, district_map.district_label, dim_group.group_name, dim_designation.designation_name, fact_batch_activity.batch_type, fact_batch_activity.batch_date, fact_batch_activity.batch_month, fact_batch_activity.implementation_status, fact_batch_activity.participants_trained, fact_batch_activity.batch_count]
    sorts: [district_map.district_label, fact_batch_activity.batch_date]
    limit: 5000
    show_view_names: false
    show_row_numbers: false
    table_theme: white
    limit_displayed_rows: false
    header_text_alignment: left
    header_font_size: "12"
    rows_font_size: "12"
    truncate_text: false
    size_to_fit: true
    total: true
    show_totals: true
    series_labels:
      dim_state.state_name: State
      district_map.district_label: District
      dim_group.group_name: Service group
      dim_designation.designation_name: Designation
      fact_batch_activity.batch_type: Programme
      fact_batch_activity.batch_date: Batch date
      fact_batch_activity.batch_month: Month
      fact_batch_activity.implementation_status: Status
      fact_batch_activity.participants_trained: Participants
      fact_batch_activity.batch_count: Batches
    listen:
      state: dim_state.state_name
      district: district_map.district_label
    tab_name: download
    row: 3
    col: 0
    width: 24
    height: 16
